In [1]:
import pandas as pd
import altair as alt

In [2]:
df = pd.read_csv('GLB.Ts_dSST.csv', skiprows=1)
df.head(150)

,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,J-D,D-N,DJF,MAM,JJA,SON
0,1880,-0.29,-0.18,-0.11,-0.19,-0.11,-0.23,-0.21,-0.09,-0.16,-0.23,-0.20,-0.23,-0.19,***,***,-0.14,-0.18,-0.20
1,1881,-0.15,-0.17,0.04,0.04,0.02,-0.20,-0.06,-0.02,-0.13,-0.20,-0.21,-0.10,-0.10,-.11,-.18,0.03,-0.09,-0.18
2,1882,0.15,0.15,0.04,-0.18,-0.16,-0.26,-0.20,-0.05,-0.10,-0.24,-0.16,-0.24,-0.10,-.09,.06,-0.10,-0.17,-0.17
3,1883,-0.31,-0.39,-0.13,-0.17,-0.20,-0.12,-0.08,-0.15,-0.20,-0.14,-0.22,-0.16,-0.19,-.20,-.31,-0.16,-0.12,-0.19
4,1884,-0.15,-0.08,-0.37,-0.42,-0.36,-0.40,-0.34,-0.26,-0.27,-0.24,-0.30,-0.28,-0.29,-.28,-.13,-0.39,-0.34,-0.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,2013,0.66,0.55,0.66,0.52,0.57,0.65,0.57,0.65,0.76,0.67,0.78,0.65,0.64,.63,.58,0.58,0.63,0.74
134,2014,0.73,0.52,0.76,0.77,0.85,0.66,0.56,0.80,0.88,0.81,0.66,0.78,0.73,.72,.63,0.79,0.67,0.78
135,2015,0.81,0.87,0.90,0.74,0.75,0.79,0.71,0.79,0.81,1.07,1.02,1.10,0.86,.84,.82,0.80,0.76,0.97
136,2016,1.15,1.34,1.30,1.07,0.90,0.78,0.82,0.99,0.87,0.89,0.90,0.82,0.99,1.01,1.19,1.09,0.86,0.88
137,2017,0.96,1.11,1.13,0.93,0.88,0.70,0.81,0.86,0.74,0.88,0.87,0.89,0.90,.89,.96,0.98,0.79,0.83

In [3]:
df = df.drop(['Jan','Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'D-N', 'DJF', 'MAM', 'JJA', 'SON'],  axis=1)
df.head()

   Year   J-D
0  1880 -0.19
1  1881 -0.10
2  1882 -0.10
3  1883 -0.19
4  1884 -0.29

In [4]:
points_left = df[df['Year'].isin([1904, 1998])]
points_right = df[df['Year'].isin([1944, 2014, 2015, 2016, 2017])]

In [5]:
text_points_left = alt.Chart(points_left).mark_text(
        align='left',
        fontSize=15,  
        fontWeight = 200,
        dx=-40
    ).encode(
        x='Year:Q',
        y='J-D:Q',
        text='Year:O'
)

text_points_right = alt.Chart(points_right).mark_text(
        align='right',
        fontSize=15,  
        fontWeight = 200,
        dx=40,
        
    ).encode(
        x='Year:Q',
        y='J-D:Q',
        text='Year:O'
)

text_bold_point = alt.Chart(points_right).mark_text(
        align='right',
        fontSize=15,  
        fontWeight = 'bold',
        dx=40,
    ).encode(
        x='Year:Q',
        y='J-D:Q',
        text='Year:O'
).transform_filter(
    alt.FieldEqualPredicate(field='Year', equal=2016)
)

In [132]:
text_upper_line = alt.Chart({'values':[{'Year': 2020, 'Temp': 0.1}]}).mark_text(
        align='right',
        fontSize=15,
    fontWeight = 200,
        text='HOTTER THAN THE \n1880-1899 AVERAGE', 
        lineBreak='\n'
    ).encode(
        x='Year:Q',
        y='Temp:Q'
)

text_under_line = alt.Chart({'values':[{'Year': 2020, 'Temp': -0.05}]}).mark_text(
        align='right',
        fontSize=15,
        fontWeight = 200,
        text='COLDER', 
    ).encode(
        x='Year:Q',
        y='Temp:Q'
)

chart_title = alt.Chart({'values':[{'Year': 1885, 'Temp': 0.99}]}).mark_text(
        align='left',
        fontSize=15,
        fontWeight = 'bold',
    opacity=1,
        text='Annual Global Surface Temperature, \nRelative to Late 19th Century Average',
        lineBreak='\n'
 
    ).encode(
        x='Year:Q',
        y='Temp:Q'
)

In [139]:
chart = alt.Chart(df).mark_point(
    filled = True, 
    color = '#F26C08', 
    stroke='#000000', 
    strokeOpacity=0.5,
    size=90).encode(
        x = alt.X(
            field='Year',  
            type = 'quantitative',
            title='',
            scale=alt.Scale(domain=[1880, 2020]),
            axis = alt.Axis(
                 format = "1000f",
                 tickMinStep = 10,
                 tickCount=14,
                 tickColor='white',
                 labelPadding=10,
                 labelFontSize=15,
                 labelOpacity=0.5,
                 labelColor='#999999',
                 domainColor='white',
             ),
        ),
        y = alt.Y(
            field='J-D', 
            type = 'quantitative',
            title='',   
            axis = alt.Axis(
                labelExpr = "format(datum.value, '+.1f') +'Â°'",
                tickMinStep = 0.2,
                tickCount=9,
                tickColor='grey',
                tickOpacity=0.3,
                labelPadding=10,
                labelFontSize=15,
                labelOpacity=0.5,
                labelColor='#999999',
                domainOpacity=0
            )
        )
)


text = chart.mark_text(
    align='left',
    baseline='middle',
    dx=7
).encode(
    text='Label'
)

In [140]:
line = alt.Chart(pd.DataFrame({'y': [0]})).mark_rule(color='black', opacity=0.5).encode(y='y')

In [141]:
chart_total = alt.layer(chart, line, text_upper_line, text_under_line, chart_title, text_points_left, text_points_right, text_bold_point).configure_view(
    strokeWidth = 0).properties(
    width = 950, height = 600, background = '#FFFFFF', padding = 25)
chart_total

alt.LayerChart(...)